# Train set

In [1]:
import os
import glob
import pandas as pd
os.chdir("../ML-for-stock-port-management/labeled-stock")

In [2]:
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
len(all_filenames)

1187

In [3]:
# create csv file with header
df = pd.read_csv(all_filenames[0])
df = pd.DataFrame(columns = df.columns)
df.to_csv('../stock.csv', index=None)

In [4]:
for i in range(len(all_filenames)):
    df = pd.read_csv(all_filenames[i])
    df25 = df.loc[25:,]
    df25.to_csv('../stock.csv', mode='a', index=None, header=False)

In [5]:
df = pd.read_csv('../stock.csv')
df.head()

,Date,Symbol,Open,High,Low,Last,ChangePercent,Volumn,Money,Net5D,...,SMA12,SMA26,MACD,MACD5,MACD10,Vol5,RSI,RSI5,Money5,Status
0,7/25/2017,2S-W1,1.18,1.19,1.11,1.13,-4.24,1183679,1355820,53777140,...,1.162500,1.387692,-0.211104,-0.211104,-0.211104,8700893.0,21.428571,22.857143,10755428.0,0.0
1,7/26/2017,2S-W1,1.14,1.17,1.13,1.15,1.77,1034870,1187180,23603650,...,1.164167,1.351923,-0.174979,-0.193041,-0.193041,3818884.6,28.571429,22.857143,4720730.0,0.0
2,7/27/2017,2S-W1,1.15,1.17,1.14,1.15,0.00,497605,573360,11764790,...,1.166667,1.320769,-0.144017,-0.176700,-0.176700,1954325.8,28.571429,24.285714,2352958.0,0.0
3,7/31/2017,2S-W1,1.16,1.25,1.16,1.18,2.61,2447900,2921900,6909320,...,1.175833,1.293077,-0.108226,-0.159582,-0.159582,1181050.6,35.714286,27.142857,1381864.0,0.0
4,8/2/2017,2S-W1,1.26,1.41,1.26,1.39,10.32,30356339,40814480,46852740,...,1.196667,1.276154,-0.058177,-0.139301,-0.139301,7104078.6,42.857143,31.428571,9370548.0,0.0

# Test set

In [1]:
import os
import glob
import pandas as pd
os.chdir("../ML-for-stock-port-management/labeled-stock-test")

In [2]:
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
len(all_filenames)

862

In [3]:
# create csv file with header
df = pd.read_csv(all_filenames[0])
df = pd.DataFrame(columns = df.columns)
df.to_csv('../stock_test.csv', index=None)

In [4]:
for i in range(len(all_filenames)):
    df = pd.read_csv(all_filenames[i])
    df25 = df.loc[25:,]
    df25.to_csv('../stock_test.csv', mode='a', index=None, header=False)

In [5]:
df = pd.read_csv('../stock_test.csv')
df.head()

,Date,Symbol,Open,High,Low,Last,ChangePercent,Volumn,Money,Net5D,...,SMA12,SMA26,MACD,MACD5,MACD10,Vol5,RSI,RSI5,Money5,Status
0,8/16/2019,2S,2.40,2.42,2.36,2.40,0.00,1645800.0,3916890.0,13034280.0,...,2.255000,2.260769,0.006225,0.002222,0.007067,986618.6,28.571429,31.428571,2360512.0,0.0
1,8/19/2019,2S,2.44,2.50,2.44,2.48,3.33,1181982.0,2925840.0,15728340.0,...,2.271667,2.269231,0.018875,0.005695,0.007446,1188635.0,28.571429,31.428571,2871270.0,1.0
2,8/20/2019,2S,2.48,2.48,2.40,2.42,-2.42,387100.0,944070.0,15825270.0,...,2.283333,2.275385,0.018262,0.010313,0.007816,1244735.0,28.571429,31.428571,3013728.0,0.0
3,8/21/2019,2S,2.44,2.44,2.40,2.42,0.00,350024.0,845060.0,10235630.0,...,2.301667,2.281538,0.028077,0.016148,0.009309,1238879.8,28.571429,30.000000,3013312.0,0.0
4,8/22/2019,2S,2.40,2.40,2.38,2.40,-0.83,255300.0,611730.0,9243590.0,...,2.316667,2.287692,0.033476,0.020983,0.011483,764041.2,28.571429,28.571429,1848718.0,0.0